# Site settings
title: Sarit's Website
email:
description: > # this means to ignore newlines until "baseurl:"
  Website for Los Angeles based artist Sarit
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
collections:
  - imagesArt

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username:
address:
  - line:
  - line:
  # Feel free to add more lines here
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
